#!/usr/bin/env python3
# Generates INDUSTRIES / COMPANIES / RAW additions for index.html

# Already-existing company IDs (skip duplicates)
EXISTING = {
    "mercedes","bmw","audi","volvo","tesla","toyota","honda","subaru","nissan",
    "mitsubishi","mazda","suzuki","daihatsu","yamaha","kawasaki","hino","isuzu",
    "shiseido","kao","kose","pola","lion","unilever","pg","loreal","esteelauder",
    "kirin","asahi_b","sapporo","suntory","cocacola","sanyo_food","nisshin",
    "toyo_suisan","myojo","mcdonalds","mos","kfc_jp","zensho","yoshinoya",
    "jt","pmj","bat_jp",
    "google_jp","ms_jp","meta_jp","lineyahoo","rakuten","amazon_jp","hkd_tech",
    "dnt_dig","cyberagent","septeni","jp_digital","kyocera_cs","ctc","scsk",
    "workthy","recruit","persol","bizreach",
    "hitachi","hgls","panasonic","mitsubishi_e","toshiba","fujitsu","nec",
    "ibm_jp","dell_jp","hp_jp","lenovo_jp","apple_jp","anest","smc","kurita",
    "daikin","sharp","ricoh","canon","nikon","epson","brother","kyocera",
    "omron","yaskawa","yokogawa","renesas","rohm",
    "alinamin","taisho","rohto","kobayashi","sumitomo_ph","takeda","astellas",
    "daiichi","chugai","eisai","tsumura","kracie",
    "hakuhodo","dentsu","adk","tokyu_ag","pwc_jp","azusa","deloitte_jp","ey_jp",
    "murc","nri","jri","mhrt","bcg_jp","accenture","amt_law","nishimura",
    "mori_h","tmi_law",
    "mechacomic","comic_s","line_manga","piccoma","manga_k","pokemon","sanrio",
    "disney_jp","furyu","segasammy","bandai_namco","square_enix","jra","nar","keirin_jp",
    "tepco","chuden","kansai_e","tokyo_gas","jr_tokai","jr_east","jr_west",
    "tokyu_fd","mitsubishi_est","mitsui_fd","sumitomo_fd","nomura_fd",
    "mitsui_home","sekisui","daiwa_house","sumitomo_r","hebel",
    "tokyo_metro","kanagawa","osaka_pref","shibuya_w","shinjuku_w","yokohama",
    "meti","mof","soumu","mhlw","cdp_jp","ldp","komei","ishin","dpfp","chukai","rengo",
    "nagase","inabata","hanwa","paltac","arata","ohki","mitsubishi_co","mitsui_co",
    "itochu","marubeni","sumitomo_co",
    "seven_i","aeon","fast_ret","nitori","mufg","smbc","mizuho","jp_post",
    "yamato","sagawa","jal","ana","nippon_life","daiichi_life","tokio_marine",
    "ms_ins","softbank","kddi","docomo","nintendo","sony","keyence","nidec",
    "fanuc","murata","shinetsu","orix","maxell","tdk","fdk","gs_yuasa",
}

# New industries: id -> label
NEW_INDUSTRIES = [
    ("syssoft",     "システム・ソフト"),
    ("think",       "シンクタンク・コンサル"),
    ("bank",        "銀行"),
    ("securities",  "証券"),
    ("lifeins",     "生保"),
    ("nonlifeins",  "損保"),
    ("finlease",    "信販・カード・リース"),
    ("tv",          "テレビ・ラジオ"),
    ("newspaper",   "新聞・出版・通信"),
    ("elecparts",   "電子部品・機器"),
    ("elecdev",     "電機・事務機器"),
    ("autoparts",   "自動車部品"),
    ("machinery",   "機械"),
    ("foodfish",    "食品・水産"),
    ("chem",        "化学"),
    ("pharma2",     "医薬品"),
    ("textile",     "衣料・繊維"),
    ("glass",       "ガラス・土石"),
    ("steel",       "鉄鋼"),
    ("nonferrous",  "非鉄金属"),
    ("metal",       "金属製品"),
    ("othermfg",    "その他メーカー"),
    ("print",       "印刷・紙パルプ"),
    ("construction","建設"),
    ("housing",     "住宅・マンション"),
    ("realestate",  "不動産"),
    ("energy",      "電力・ガス"),
    ("oil",         "石油"),
    ("dept",        "デパート"),
    ("convenience", "コンビニ"),
    ("supermarket", "スーパー"),
    ("restaurant",  "外食・中食"),
    ("retail3",     "家電量販・薬局・HC"),
    ("otherretail", "その他小売"),
    ("gaming",      "ゲーム"),
    ("hred",        "人材・教育"),
    ("hotel",       "ホテル"),
    ("leisure",     "レジャー"),
    ("seaair",      "海運・空運"),
    ("logistics",   "運輸・倉庫"),
    ("railway",     "鉄道"),
    ("otherservice","その他サービス"),
    ("agri",        "農林"),
    ("telecom",     "通信サービス"),
    ("research",    "リサーチ"),
    ("meddevice",   "医療機器"),
    ("transport",   "輸送用機器"),
    ("cosme2",      "化粧品・トイレタリー"),
]

# company data: (id, name, url, industry_id)
# url = corporate TOP page URL
COMPANIES_NEW = [
    # ── 商社・卸売業 (new companies) ──────────────────────────────
    ("toyota_tsusho",   "豊田通商",              "https://www.toyota-tsusho.com/",          "trading"),
    ("sojitz",          "双日",                  "https://www.sojitz.com/",                 "trading"),
    ("kanematsu",       "兼松",                  "https://www.kanematsu.co.jp/",            "trading"),
    ("metalwon",        "メタルワン",            "https://www.metalwon.co.jp/",             "trading"),
    ("nittetsu_bussan", "日鉄物産",              "https://www.nbs.co.jp/",                  "trading"),
    ("honda_trading",   "ホンダトレーディング",  "https://www.honda-trading.co.jp/",        "trading"),
    ("jfe_shoji",       "JFE商事",               "https://www.jfe-shoji.co.jp/",            "trading"),
    ("okaya",           "岡谷鋼機",              "https://www.okaya.co.jp/",                "trading"),
    ("shinkosteel",     "神鋼商事",              "https://www.shinkosteel.co.jp/",          "trading"),
    ("yuasa_trading",   "ユアサ商事",            "https://www.yuasa-trading.co.jp/",        "trading"),
    ("yamazen",         "山善",                  "https://www.yamazen.co.jp/",              "trading"),
    ("misumi",          "ミスミ",                "https://www.misumi.co.jp/",               "trading"),
    ("trusco",          "トラスコ中山",          "https://www.trusco.co.jp/",               "trading"),
    ("daiwa_info",      "ダイワボウ情報システム","https://www.daiwagroup.jp/dis/",           "trading"),
    ("hitachi_ht",      "日立ハイテク",          "https://www.hitachi-hightech.com/jp/",    "trading"),
    ("canon_mj",        "キヤノンMJ",            "https://cweb.canon.jp/cmj/",              "trading"),
    ("inaba_denki",     "因幡電機産業",          "https://www.inaba-denko.com/",            "trading"),
    ("ceekx",           "シークス",              "https://www.seecs.co.jp/",                "trading"),
    ("macnica",         "マクニカ",              "https://www.macnica.co.jp/",              "trading"),
    ("kaga_elec",       "加賀電子",              "https://www.kaga-elec.co.jp/",            "trading"),
    ("ryoyo_elec",      "リョーサン菱洋HD",      "https://www.ryoyo-mitsubishi-hd.co.jp/",  "trading"),
    ("te_device",       "東京エレクトロン デバイス","https://www.teldevice.co.jp/",          "trading"),
    ("marumo",          "丸文",                  "https://www.marumo.co.jp/",               "trading"),
    ("hakuto",          "伯東",                  "https://www.hakuto.co.jp/",               "trading"),
    ("nippon_access",   "日本アクセス",          "https://www.nippon-access.co.jp/",        "trading"),
    ("kokubu",          "国分グループ",          "https://www.kokubu.co.jp/",               "trading"),
    ("mitsubishi_food", "三菱食品",              "https://www.mitsubishi-shokuhin.com/",    "trading"),
    ("kato_sangyo",     "加藤産業",              "https://www.katogroup.co.jp/",            "trading"),
    ("yamae_gp",        "ヤマエグループHD",      "https://www.yamaeholdings.co.jp/",        "trading"),
    ("itochu_food",     "伊藤忠食品",            "https://www.itochu-food.co.jp/",          "trading"),
    ("medithe",         "メディセオ",            "https://www.medipalholdings.co.jp/",      "trading"),
    ("alfresa",         "アルフレッサ",          "https://www.alfresa.com/",                "trading"),
    ("suzuken",         "スズケン",              "https://www.suzuken.co.jp/",              "trading"),
    ("toho_yaku",       "東邦薬品",              "https://www.toho-pharmaceutical.co.jp/",  "trading"),
    ("kowa",            "興和",                  "https://www.kowa.co.jp/",                 "trading"),
    ("itochu_enex",     "伊藤忠エネクス",        "https://www.itcenex.com/",                "trading"),
    ("iwatani",         "岩谷産業",              "https://www.iwatani.co.jp/",              "trading"),
    ("uchida_yoko",     "内田洋行",              "https://www.uchida.co.jp/",               "trading"),
    ("autobacs",        "オートバックスセブン",  "https://www.autobacs.co.jp/",             "trading"),
    ("doshisha",        "ドウシシャ",            "https://www.doshisha.co.jp/",             "trading"),

    # ── シンクタンク・コンサル ──────────────────────────────────
    ("mri",             "三菱総合研究所",        "https://www.mri.co.jp/",                  "think"),
    ("daiwa_research",  "大和総研",              "https://www.dir.co.jp/",                  "think"),
    ("funai",           "船井総合研究所",        "https://www.funaisoken.co.jp/",           "think"),
    ("paccon",          "パシフィックコンサルタンツ","https://www.pacific.co.jp/",           "think"),
    ("intage",          "インテージ",            "https://www.intage.co.jp/",               "think"),
    ("teikoku_db",      "帝国データバンク",      "https://www.tdb.co.jp/",                  "think"),
    ("tsr",             "東京商工リサーチ",      "https://www.tsr-net.co.jp/",              "think"),
    ("macromill",       "マクロミル",            "https://www.macromill.com/",              "think"),

    # ── 通信サービス ────────────────────────────────────────────
    ("ntt",             "NTT",                   "https://www.ntt.co.jp/",                  "telecom"),
    ("ntt_east",        "NTT東日本",             "https://www.ntt-east.co.jp/",             "telecom"),
    ("ntt_west",        "NTT西日本",             "https://www.ntt-west.co.jp/",             "telecom"),
    ("jcom",            "JCOM",                  "https://www.jcom.co.jp/",                 "telecom"),
    ("deena",           "DeNA",                  "https://dena.com/jp/",                    "telecom"),
    ("mixi",            "MIXI",                  "https://mixi.co.jp/",                     "telecom"),
    ("zenrin",          "ゼンリン",              "https://www.zenrin.co.jp/",               "telecom"),
    ("gurunavi",        "ぐるなび",              "https://pr.gnavi.co.jp/",                 "telecom"),
    ("infocom",         "インフォコム",          "https://www.infocom.co.jp/",              "telecom"),

    # ── システム・ソフト ────────────────────────────────────────
    ("nttdata",         "NTTデータグループ",     "https://www.nttdata.com/jp/ja/",          "syssoft"),
    ("otsuka_shokai",   "大塚商会",              "https://www.otsuka-shokai.co.jp/",        "syssoft"),
    ("tis",             "TIS",                   "https://www.tis.co.jp/",                  "syssoft"),
    ("hitachi_sys",     "日立システムズ",        "https://www.hitachi-systems.com/",        "syssoft"),
    ("biprogy",         "BIPROGY",               "https://www.biprogy.com/",                "syssoft"),
    ("ns_sol",          "日鉄ソリューションズ",  "https://www.nssol.nipponsteel.com/",      "syssoft"),
    ("nec_netsi",       "NECネッツエスアイ",     "https://www.nesic.co.jp/",                "syssoft"),
    ("fuji_soft",       "富士ソフト",            "https://www.fsi.co.jp/",                  "syssoft"),
    ("nec_sol",         "NECソリューションイノベータ","https://www.nec-solutioninnovators.co.jp/","syssoft"),
    ("gmo",             "GMOインターネットG",    "https://www.gmo.jp/",                     "syssoft"),
    ("oracle_jp",       "日本オラクル",          "https://www.oracle.com/jp/",              "syssoft"),
    ("toyota_sys",      "トヨタシステムズ",      "https://www.toyotasystems.com/",          "syssoft"),
    ("hitachi_sol",     "日立ソリューションズ",  "https://www.hitachi-solutions.co.jp/",    "syssoft"),
    ("uniadex",         "ユニアデックス",        "https://www.uniadex.co.jp/",              "syssoft"),
    ("dentsu_soken",    "電通総研",              "https://www.dentsusoken.com/",            "syssoft"),
    ("panasonic_is",    "パナソニック IS",       "https://www.panasonic.com/jp/company/pis/","syssoft"),
    ("nbs_jp",          "日本ビジネスシステムズ","https://www.nbs.co.jp/",                  "syssoft"),
    ("dts",             "DTS",                   "https://www.dts.co.jp/",                  "syssoft"),
    ("intec",           "インテック",            "https://www.intec.co.jp/",                "syssoft"),
    ("sky_co",          "Sky",                   "https://www.skygroup.jp/",                "syssoft"),
    ("obic",            "オービック",            "https://www.obic.co.jp/",                 "syssoft"),
    ("mufg_it",         "三菱UFJ IT",            "https://www.muit.co.jp/",                 "syssoft"),
    ("nsd",             "NSD",                   "https://www.nsd.co.jp/",                  "syssoft"),
    ("kanematsu_elec",  "兼松エレクトロニクス",  "https://www.kec.co.jp/",                  "syssoft"),
    ("tsuzuki_elec",    "都築電気",              "https://www.tsuzuki.co.jp/",              "syssoft"),
    ("systena",         "システナ",              "https://www.systena.co.jp/",              "syssoft"),
    ("tkc",             "TKC",                   "https://www.tkc.co.jp/",                  "syssoft"),
    ("jbcc",            "JBCCホールディングス",  "https://www.jbcc.co.jp/",                 "syssoft"),
    ("jsol",            "JSOL",                  "https://www.jsol.co.jp/",                 "syssoft"),
    ("simplex",         "シンプレクスHD",        "https://www.simplex.inc/",                "syssoft"),
    ("obic_biz",        "オービックBC",          "https://www.obc.co.jp/",                  "syssoft"),
    ("zuken",           "図研",                  "https://www.zuken.co.jp/",                "syssoft"),
    ("netone",          "ネットワンシステムズ",  "https://www.netone.co.jp/",               "syssoft"),

    # ── 銀行 ──────────────────────────────────────────────────
    ("yucho",           "ゆうちょ銀行",          "https://www.jp-bank.japanpost.jp/",       "bank"),
    ("resona",          "りそなグループ",        "https://www.resona-gr.co.jp/",            "bank"),
    ("sbi_shinsei",     "SBI新生銀行",           "https://www.sbishinseibank.co.jp/",       "bank"),
    ("aozora",          "あおぞら銀行",          "https://www.aozorabank.co.jp/",           "bank"),
    ("seven_bank",      "セブン銀行",            "https://www.sevenbank.co.jp/",            "bank"),
    ("sbi_net",         "住信SBIネット銀行",     "https://www.netbk.co.jp/",                "bank"),
    ("smtrust",         "三井住友信託銀行",      "https://www.smtb.jp/",                    "bank"),
    ("mufg_trust",      "三菱UFJ信託銀行",       "https://www.tr.mufg.jp/",                 "bank"),
    ("hokkaido_bank",   "北海道銀行",            "https://www.hokkaidobank.co.jp/",         "bank"),
    ("aomori_bank",     "青森みちのく銀行",      "https://www.michinokubank.co.jp/",        "bank"),
    ("iwate_bank",      "岩手銀行",              "https://www.iwatebank.co.jp/",            "bank"),
    ("akita_bank",      "秋田銀行",              "https://www.akita-bank.co.jp/",           "bank"),
    ("yamagata_bank",   "山形銀行",              "https://www.yamagatabank.co.jp/",         "bank"),
    ("jyoyo_bank",      "常陽銀行",              "https://www.joyobank.co.jp/",             "bank"),
    ("ashikaga",        "足利銀行",              "https://www.ashikagabank.co.jp/",         "bank"),
    ("gunma_bank",      "群馬銀行",              "https://www.gunmabank.co.jp/",            "bank"),
    ("chiba_bank",      "千葉銀行",              "https://www.chibabank.co.jp/",            "bank"),
    ("yokohama_bank",   "横浜銀行",              "https://www.boy.co.jp/",                  "bank"),
    ("daishi_bank",     "第四北越銀行",          "https://www.dhbk.co.jp/",                 "bank"),
    ("hokuriku_bank",   "北陸銀行",              "https://www.hokugin.co.jp/",              "bank"),
    ("fukui_bank",      "福井銀行",              "https://www.fukuibank.co.jp/",            "bank"),
    ("yamanashi_bank",  "山梨中央銀行",          "https://www.yamanashibank.co.jp/",        "bank"),
    ("hachijuni",       "八十二銀行",            "https://www.82bank.co.jp/",               "bank"),
    ("juroku",          "十六フィナンシャルG",   "https://www.juroku.co.jp/",               "bank"),
    ("shizuoka_bank",   "静岡銀行",              "https://www.shizuokabank.co.jp/",         "bank"),
    ("suruga",          "スルガ銀行",            "https://www.surugabank.co.jp/",           "bank"),
    ("nagoya_bank",     "名古屋銀行",            "https://www.meigin.com/",                 "bank"),
    ("hyakugo",         "百五銀行",              "https://www.hyakugo.co.jp/",              "bank"),
    ("shiga_bank",      "滋賀銀行",              "https://www.shigagin.com/",               "bank"),
    ("kyoto_bank",      "京都銀行",              "https://www.kyotobank.co.jp/",            "bank"),
    ("kansai_mirai",    "関西みらい銀行",        "https://www.kansaimirai.co.jp/",          "bank"),
    ("nanto_bank",      "南都銀行",              "https://www.nantobank.co.jp/",            "bank"),
    ("kiyo_bank",       "紀陽銀行",              "https://www.kiyobank.co.jp/",             "bank"),
    ("sanin_bank",      "山陰合同銀行",          "https://www.gogin.co.jp/",                "bank"),
    ("chugoku_bank",    "中国銀行",              "https://www.chugin.co.jp/",               "bank"),
    ("awa_bank",        "阿波銀行",              "https://www.awabank.co.jp/",              "bank"),
    ("iyo_bank",        "伊予銀行",              "https://www.iyobank.co.jp/",              "bank"),
    ("fukuoka_bank",    "福岡銀行",              "https://www.fukuokabank.co.jp/",          "bank"),
    ("saga_bank",       "佐賀銀行",              "https://www.sagabank.co.jp/",             "bank"),
    ("higo_bank",       "肥後銀行",              "https://www.higobank.co.jp/",             "bank"),
    ("kagoshima_bank",  "鹿児島銀行",            "https://www.kagin.co.jp/",                "bank"),
    ("ryukyu_bank",     "琉球銀行",              "https://www.ryugin.co.jp/",               "bank"),
    ("okinawa_bank",    "沖縄銀行",              "https://www.okinawa-bank.co.jp/",         "bank"),
    ("shoko_chukin",    "商工中金",              "https://www.shokochukin.co.jp/",          "bank"),
    ("jbic",            "国際協力銀行",          "https://www.jbic.go.jp/",                 "bank"),

    # ── 証券 ──────────────────────────────────────────────────
    ("sbi_hd",          "SBIホールディングス",   "https://www.sbigroup.co.jp/",             "securities"),
    ("daiwa_sec",       "大和証券グループ",      "https://www.daiwa-grp.jp/",               "securities"),
    ("nomura_sec",      "野村證券",              "https://www.nomura.co.jp/",               "securities"),
    ("mizuho_sec",      "みずほ証券",            "https://www.mizuho-sc.com/",              "securities"),
    ("smbc_nikko",      "SMBC日興証券",          "https://www.smbcnikko.co.jp/",            "securities"),
    ("mufg_morgan",     "三菱UFJモルガンS証券",  "https://www.sc.mufg.jp/",                 "securities"),
    ("jpx",             "日本取引所グループ",    "https://www.jpx.co.jp/",                  "securities"),
    ("tokai_tokyo",     "東海東京FHD",           "https://www.tokaitokyo-fhd.co.jp/",       "securities"),
    ("okasan",          "岡三証券",              "https://www.okasan.co.jp/",               "securities"),
    ("matsui_sec",      "松井証券",              "https://www.matsui.co.jp/",               "securities"),

    # ── 生保 ──────────────────────────────────────────────────
    ("kampo_life",      "かんぽ生命保険",        "https://www.jp-life.japanpost.jp/",       "lifeins"),
    ("sumitomo_life",   "住友生命保険",          "https://www.sumitomolife.co.jp/",         "lifeins"),
    ("sony_life",       "ソニー生命保険",        "https://www.sonylife.co.jp/",             "lifeins"),
    ("aflac",           "アフラック生命保険",    "https://www.aflac.co.jp/",                "lifeins"),
    ("axa_life",        "アクサ生命保険",        "https://www.axa.co.jp/",                  "lifeins"),
    ("daido_life",      "大同生命保険",          "https://www.daido-life.co.jp/",           "lifeins"),
    ("taiyo_life",      "太陽生命保険",          "https://www.taiyo-seimei.co.jp/",         "lifeins"),
    ("tokiomarine_life","東京海上日動あんしん生命","https://www.tmn-anshin.co.jp/",          "lifeins"),
    ("orix_life",       "オリックス生命保険",    "https://www.orixlife.co.jp/",             "lifeins"),
    ("sompo_himawari",  "SOMPOひまわり生命",     "https://www.sompo-himawari.co.jp/",       "lifeins"),
    ("asahi_life",      "朝日生命保険",          "https://www.asahi-life.co.jp/",           "lifeins"),

    # ── 損保 ──────────────────────────────────────────────────
    ("sompo",           "損害保険ジャパン",      "https://www.sompo-japan.co.jp/",          "nonlifeins"),
    ("aioi_nissay",     "あいおいニッセイ同和損保","https://www.aioinissaydowa.co.jp/",      "nonlifeins"),
    ("kyoei_fire",      "共栄火災海上保険",      "https://www.kyoeikasai.co.jp/",           "nonlifeins"),
    ("nisshin_fire",    "日新火災海上保険",       "https://www.nisshinfire.co.jp/",          "nonlifeins"),
    ("sony_ins",        "ソニー損害保険",        "https://www.sonysonpo.co.jp/",            "nonlifeins"),

    # ── 信販・カード・リース ────────────────────────────────────
    ("orix",            "オリックス",            "https://www.orix.co.jp/",                 "finlease"),
    ("smfl",            "三井住友F&L",           "https://www.smfl.co.jp/",                 "finlease"),
    ("mhc",             "三菱HCキャピタル",      "https://www.mitsubishi-hc-capital.com/",  "finlease"),
    ("tokyo_century",   "東京センチュリー",      "https://www.tokyocentury.co.jp/",         "finlease"),
    ("mizuho_lease",    "みずほリース",          "https://www.mizuho-ls.co.jp/",            "finlease"),
    ("smbc_cf",         "SMBCコンシューマーF",   "https://www.smbc-cf.com/",                "finlease"),
    ("jcb",             "ジェーシービー",        "https://www.jcb.co.jp/",                  "finlease"),
    ("smbc_card",       "三井住友カード",        "https://www.smbc-card.com/",              "finlease"),
    ("credit_saison",   "クレディセゾン",        "https://www.saisoncard.co.jp/",           "finlease"),
    ("acom",            "アコム",                "https://www.acom.co.jp/",                 "finlease"),
    ("aiful",           "アイフル",              "https://www.aiful.co.jp/",                "finlease"),
    ("jaccs",           "ジャックス",            "https://www.jaccs.co.jp/",                "finlease"),
    ("orientcorp",      "オリエントコーポレーション","https://www.orico.co.jp/",             "finlease"),
    ("aeon_fin",        "イオンフィナンシャルS",  "https://www.aeon-financial.co.jp/",       "finlease"),

    # ── テレビ・ラジオ ───────────────────────────────────────
    ("ntv",             "日本テレビ放送網",      "https://www.ntv.co.jp/",                  "tv"),
    ("tv_asahi",        "テレビ朝日",            "https://www.tv-asahi.co.jp/",             "tv"),
    ("tv_tokyo",        "テレビ東京",            "https://www.tv-tokyo.co.jp/",             "tv"),
    ("chukyotv",        "中京テレビ放送",        "https://www.ctv.co.jp/",                  "tv"),
    ("abc_tv",          "朝日放送テレビ",        "https://www.asahi.co.jp/",                "tv"),
    ("mbs",             "毎日放送",              "https://www.mbs.jp/",                     "tv"),
    ("ytv",             "読売テレビ放送",        "https://www.ytv.co.jp/",                  "tv"),
    ("kansai_tv",       "関西テレビ放送",        "https://www.ktv.jp/",                     "tv"),
    ("tv_osaka",        "テレビ大阪",            "https://www.tv-osaka.co.jp/",             "tv"),
    ("nippon_hoso",     "ニッポン放送",          "https://www.1242.com/",                   "tv"),

    # ── 広告 (new, supplement adcons) ────────────────────────
    ("jr_east_plan",    "ジェイアール東日本企画","https://www.jeki.co.jp/",                 "adcons"),
    ("yomiuri_is",      "読売IS",                "https://www.yomiuri-is.co.jp/",           "adcons"),
    ("asahi_adv",       "朝日広告社",            "https://www.asahi-adv.co.jp/",            "adcons"),
    ("carta",           "CARTA HOLDINGS",        "https://cartaholdings.co.jp/",            "adcons"),
    ("dnt_east",        "電通東日本",            "https://www.dentsuhigashi.co.jp/",        "adcons"),

    # ── 新聞・出版・通信 ──────────────────────────────────────
    ("nikkei",          "日本経済新聞社",        "https://www.nikkei.co.jp/",               "newspaper"),
    ("asahi_shimbun",   "朝日新聞社",            "https://www.asahi.com/",                  "newspaper"),
    ("yomiuri",         "読売新聞社",            "https://www.yomiuri.co.jp/",              "newspaper"),
    ("mainichi",        "毎日新聞社",            "https://mainichi.jp/",                    "newspaper"),
    ("chunichi",        "中日新聞社",            "https://www.chunichi.co.jp/",             "newspaper"),
    ("sankei",          "産業経済新聞社",        "https://www.sankei.com/",                 "newspaper"),
    ("hokkaido_np",     "北海道新聞社",          "https://www.hokkaido-np.co.jp/",          "newspaper"),
    ("kyodo",           "共同通信社",            "https://www.kyodo.co.jp/",                "newspaper"),
    ("jiji",            "時事通信社",            "https://www.jiji.com/",                   "newspaper"),
    ("kadokawa",        "KADOKAWA",              "https://www.kadokawa.co.jp/",             "newspaper"),
    ("kodansha",        "講談社",                "https://www.kodansha.co.jp/",             "newspaper"),
    ("toyo_keizai",     "東洋経済新報社",        "https://toyokeizai.net/",                 "newspaper"),
    ("gakken",          "学研グループ",          "https://www.gakken.co.jp/",               "newspaper"),
    ("spacajsat",       "スカパーJSAT",          "https://www.skyperfectjsat.space/",       "newspaper"),
    ("sonymusicrp",     "ソニーミュージックG",   "https://www.sonymusic.co.jp/",            "newspaper"),

    # ── 電機・事務機器 ────────────────────────────────────────
    ("jvc_kenwood",     "JVCケンウッド",         "https://www.jvckenwood.com/jp/",          "elecdev"),
    ("casio",           "カシオ計算機",          "https://www.casio.com/jp/",               "elecdev"),
    ("buffalo",         "バッファロー",          "https://www.buffalo.jp/",                 "elecdev"),
    ("zojirushi",       "象印マホービン",        "https://www.zojirushi.co.jp/",            "elecdev"),
    ("fujixerox",       "富士フイルムBI",        "https://www.fujifilm.com/fb/",            "elecdev"),
    ("konica_minolta",  "コニカミノルタ",        "https://www.konicaminolta.jp/",           "elecdev"),
    ("toshiba_tec",     "東芝テック",            "https://www.toshibatec.co.jp/",           "elecdev"),
    ("kyocera_doc",     "京セラドキュメントS",   "https://www.kyoceradocumentsolutions.co.jp/","elecdev"),
    ("oki",             "沖電気工業",            "https://www.oki.com/jp/",                 "elecdev"),
    ("fuji_electric",   "富士電機",              "https://www.fujielectric.co.jp/",         "elecdev"),
    ("shimadzu",        "島津製作所",            "https://www.shimadzu.co.jp/",             "elecdev"),
    ("horiba",          "堀場製作所",            "https://www.horiba.com/jpn/",             "elecdev"),
    ("meidensha",       "明電舎",                "https://www.meidensha.co.jp/",            "elecdev"),
    ("daihen",          "ダイヘン",              "https://www.daihen.co.jp/",               "elecdev"),
    ("jeol",            "日本電子",              "https://www.jeol.co.jp/",                 "elecdev"),
    ("nitto_kogyo",     "日東工業",              "https://www.nitto-kogyo.co.jp/",          "elecdev"),
    ("ishida",          "イシダ",                "https://www.ishida.co.jp/",               "elecdev"),
    ("nichishin_elec",  "日新電機",              "https://www.nisshinelec.co.jp/",          "elecdev"),
    ("nohmi",           "能美防災",              "https://www.nohmi.co.jp/",               "elecdev"),
    ("furuno",          "古野電気",              "https://www.furuno.com/jp/",              "elecdev"),
    ("nippon_signal",   "日本信号",              "https://www.signal.co.jp/",               "elecdev"),

    # ── 電子部品・機器 ───────────────────────────────────────
    ("nidec_new",       "ニデック",              "https://www.nidec.com/ja-JP/",            "elecparts"),
    ("kioxia",          "キオクシア",            "https://www.kioxia.com/ja-JP/",           "elecparts"),
    ("minebea",         "ミネベアミツミ",        "https://www.minebeamitsumi.com/ja/",      "elecparts"),
    ("nitto_denko",     "日東電工",              "https://www.nitto.com/jp/ja/",            "elecparts"),
    ("alps_alpine",     "アルプスアルパイン",    "https://www.alpsalpine.com/j/",           "elecparts"),
    ("nichia",          "日亜化学工業",          "https://www.nichia.co.jp/",               "elecparts"),
    ("ibiden",          "イビデン",              "https://www.ibiden.co.jp/",               "elecparts"),
    ("taiyo_yuden",     "太陽誘電",              "https://www.yuden.co.jp/jp/",             "elecparts"),
    ("citizen",         "シチズン時計",          "https://www.citizen.co.jp/",              "elecparts"),
    ("seiko",           "セイコーグループ",      "https://www.seiko.co.jp/",                "elecparts"),
    ("azbil",           "アズビル",              "https://www.azbil.com/jp/",               "elecparts"),
    ("topcon",          "トプコン",              "https://www.topcon.co.jp/",               "elecparts"),
    ("hamamatsu",       "浜松ホトニクス",        "https://www.hamamatsu.com/jp/ja/",        "elecparts"),
    ("mabuchi",         "マブチモーター",        "https://www.mabuchi-motor.co.jp/",        "elecparts"),
    ("hirose",          "ヒロセ電機",            "https://www.hirose.com/ja/",              "elecparts"),
    ("socionext",       "ソシオネクスト",        "https://www.socionext.com/jp/",           "elecparts"),
    ("nichicon",        "ニチコン",              "https://www.nichicon.co.jp/",             "elecparts"),
    ("tel",             "東京エレクトロン",      "https://www.tel.com/ja/",                 "elecparts"),
    ("advantest",       "アドバンテスト",        "https://www.advantest.com/ja/",           "elecparts"),
    ("screen",          "SCREENホールディングス","https://www.screen.co.jp/",                "elecparts"),
    ("disco",           "ディスコ",              "https://www.disco.co.jp/",                "elecparts"),
    ("lasertech",       "レーザーテック",        "https://www.lasertech.co.jp/",            "elecparts"),
    ("ulvac",           "アルバック",            "https://www.ulvac.co.jp/",                "elecparts"),
    ("ushio",           "ウシオ電機",            "https://www.ushio.co.jp/",                "elecparts"),
    ("tamron",          "タムロン",              "https://www.tamron.com/jp/",              "elecparts"),
    ("anritsu",         "アンリツ",              "https://www.anritsu.com/ja-JP/",          "elecparts"),

    # ── 医療機器 ─────────────────────────────────────────────
    ("terumo",          "テルモ",                "https://www.terumo.co.jp/",               "meddevice"),
    ("nipro",           "ニプロ",                "https://www.nipro.co.jp/",                "meddevice"),
    ("canon_medical",   "キヤノンメディカルS",   "https://jp.medical.canon/",               "meddevice"),
    ("sysmex",          "シスメックス",          "https://www.sysmex.co.jp/",               "meddevice"),
    ("nihon_kohden",    "日本光電",              "https://www.nihonkohden.co.jp/",          "meddevice"),
    ("nikkiso",         "日機装",                "https://www.nikkiso.co.jp/",              "meddevice"),
    ("hochiki",         "ホーチキ",              "https://www.hochiki.co.jp/",              "meddevice"),

    # ── 自動車部品 ────────────────────────────────────────────
    ("denso",           "デンソー",              "https://www.denso.com/jp/ja/",            "autoparts"),
    ("aisin",           "アイシン",              "https://www.aisin.com/jp/",               "autoparts"),
    ("toyota_boshoku",  "トヨタ紡織",            "https://www.toyota-boshoku.com/jp/",      "autoparts"),
    ("toyoda_gosei",    "豊田合成",              "https://www.toyoda-gosei.co.jp/",         "autoparts"),
    ("tokai_rika",      "東海理化",              "https://www.tokai-rika.co.jp/",           "autoparts"),
    ("bridgestone",     "ブリヂストン",          "https://www.bridgestone.co.jp/",          "autoparts"),
    ("sumitomo_rubber", "住友ゴム工業",          "https://www.srigroup.co.jp/",             "autoparts"),
    ("yokohama_rubber", "横浜ゴム",              "https://www.y-yokohama.com/",             "autoparts"),
    ("toyo_tire",       "TOYO TIRE",             "https://www.toyotires.jp/",               "autoparts"),
    ("toyota_jidoshokki","豊田自動織機",         "https://www.toyota-industries.com/jp/",   "autoparts"),
    ("nok",             "NOK",                   "https://www.nok.co.jp/",                  "autoparts"),
    ("stanley",         "スタンレー電気",        "https://www.stanley.co.jp/",              "autoparts"),
    ("nissen_hd",       "日清紡HD",              "https://www.nisshinbo.co.jp/",            "autoparts"),
    ("nhk_spring",      "日本発条",              "https://www.nhkspg.co.jp/",               "autoparts"),
    ("jtekt",           "ジェイテクト",          "https://www.jtekt.co.jp/",                "autoparts"),
    ("kayaba",          "カヤバ",                "https://www.kyb.co.jp/",                  "autoparts"),
    ("musashi_seimitsu","武蔵精密工業",          "https://www.musashi.co.jp/",              "autoparts"),
    ("exedy",           "エクセディ",            "https://www.exedy.com/jp/",               "autoparts"),
    ("sumitomo_wiring",  "住友電装",             "https://www.sws.co.jp/",                  "autoparts"),
    ("yazaki",          "矢崎総業",              "https://www.yazaki-group.com/global/jp/", "autoparts"),

    # ── 輸送用機器 ────────────────────────────────────────────
    ("imabari",         "今治造船",              "https://www.imazo.co.jp/",                "transport"),
    ("jmu",             "ジャパン マリンユナイテッド","https://www.jmuc.co.jp/",              "transport"),
    ("shinmeiwa",       "新明和工業",            "https://www.shinmaywa.co.jp/",            "transport"),
    ("morita_hd",       "モリタホールディングス","https://www.morita119.com/",              "transport"),
    ("shimano",         "シマノ",                "https://corporate.shimano.co.jp/",        "transport"),

    # ── 機械 ─────────────────────────────────────────────────
    ("mitsubishi_hvy",  "三菱重工業",            "https://www.mhi.com/jp/",                 "machinery"),
    ("kawasaki_hvy",    "川崎重工業",            "https://www.khi.co.jp/",                  "machinery"),
    ("kubota",          "クボタ",                "https://www.kubota.co.jp/",               "machinery"),
    ("hitachi_kenki",   "日立建機",              "https://www.hitachicm.com/jp/",           "machinery"),
    ("yanmar",          "ヤンマーHD",            "https://www.yanmar.com/jp/",              "machinery"),
    ("kobelco_kenki",   "コベルコ建機",          "https://www.kobelco-kenki.co.jp/",        "machinery"),
    ("tadano",          "タダノ",                "https://www.tadano.co.jp/",               "machinery"),
    ("komatsu",         "コマツ",                "https://www.komatsu.co.jp/",              "machinery"),
    ("hoshizaki",       "ホシザキ",              "https://www.hoshizaki.co.jp/",            "machinery"),
    ("amano",           "アマノ",                "https://www.amano.co.jp/",                "machinery"),
    ("kittz",           "キッツ",                "https://www.kitz.co.jp/",                 "machinery"),
    ("ebara",           "荏原製作所",            "https://www.ebara.co.jp/",                "machinery"),
    ("miura_ind",       "三浦工業",              "https://www.miuraz.co.jp/",               "machinery"),
    ("sumitomo_hvy",    "住友重機械工業",        "https://www.shi.co.jp/",                  "machinery"),
    ("makita",          "マキタ",                "https://www.makita.co.jp/",               "machinery"),
    ("daifuku",         "ダイフク",              "https://www.daifuku.com/jp/",             "machinery"),
    ("nabtesco",        "ナブテスコ",            "https://www.nabtesco.com/ja/",            "machinery"),
    ("tsubakimoto",     "椿本チエイン",          "https://www.tsubakimoto.jp/",             "machinery"),
    ("fujitec",         "フジテック",            "https://www.fujitec.co.jp/",              "machinery"),
    ("ckd_corp",        "CKD",                   "https://www.ckd.co.jp/",                  "machinery"),
    ("osg",             "オーエスジー",          "https://www.osg.co.jp/",                  "machinery"),
    ("mitutoyo",        "ミツトヨ",              "https://www.mitutoyo.co.jp/",             "machinery"),
    ("dmg_mori",        "DMG森精機",             "https://jp.dmgmori.com/",                 "machinery"),
    ("amada",           "アマダ",                "https://www.amada.co.jp/",                "machinery"),
    ("okuma",           "オークマ",              "https://www.okuma.co.jp/",                "machinery"),
    ("nachi",           "不二越",                "https://www.nachi-fujikoshi.co.jp/",      "machinery"),
    ("metawater",       "メタウォーター",        "https://www.metawater.co.jp/",            "machinery"),
    ("organo",          "オルガノ",              "https://www.organo.co.jp/",               "machinery"),
    ("takuma",          "タクマ",                "https://www.takuma.co.jp/",               "machinery"),
    ("ntn",             "NTN",                   "https://www.ntn.co.jp/",                  "machinery"),
    ("nsk",             "日本精工",              "https://www.nsk.com/jp/",                 "machinery"),
    ("thk",             "THK",                   "https://www.thk.com/jp/",                 "machinery"),

    # ── 食品・水産 ────────────────────────────────────────────
    ("yakult",          "ヤクルト本社",          "https://www.yakult.co.jp/",               "foodfish"),
    ("itoen",           "伊藤園",                "https://www.itoen.co.jp/",                "foodfish"),
    ("asahi_soft",      "アサヒ飲料",            "https://www.asahiinryo.co.jp/",           "foodfish"),
    ("dydo",            "ダイドードリンコ",      "https://www.dydo.co.jp/",                 "foodfish"),
    ("agf",             "味の素AGF",             "https://www.agf.co.jp/",                  "foodfish"),
    ("key_coffee",      "キーコーヒー",          "https://www.keycoffee.co.jp/",            "foodfish"),
    ("yukijirushi",     "雪印メグミルク",        "https://www.meg-snow.com/",               "foodfish"),
    ("morinaga_dairy",  "森永乳業",              "https://www.morinagamilk.co.jp/",         "foodfish"),
    ("takarashuzo",     "宝ホールディングス",    "https://www.takara.co.jp/",               "foodfish"),
    ("ajinomoto",       "味の素",                "https://www.ajinomoto.co.jp/",            "foodfish"),
    ("meiji",           "明治",                  "https://www.meiji.co.jp/",                "foodfish"),
    ("nichirei",        "ニチレイ",              "https://www.nichirei.co.jp/",             "foodfish"),
    ("fuji_oil",        "不二製油",              "https://www.fujioilgroup.com/ja/",        "foodfish"),
    ("nisshin_oillio",  "日清オイリオG",         "https://www.nisshin-oillio.com/",         "foodfish"),
    ("house_foods",     "ハウス食品G",           "https://housefoods-group.com/",           "foodfish"),
    ("kagome",          "カゴメ",                "https://www.kagome.co.jp/",               "foodfish"),
    ("asahi_group_f",   "アサヒグループ食品",    "https://www.asahi-gf.co.jp/",             "foodfish"),
    ("mizkan",          "ミツカングループ",       "https://www.mizkan.co.jp/",               "foodfish"),
    ("sbfoods",         "エスビー食品",          "https://www.sbfoods.co.jp/",              "foodfish"),
    ("kikkoman",        "キッコーマン",          "https://www.kikkoman.co.jp/",             "foodfish"),
    ("kewpie",          "キユーピー",            "https://www.kewpie.co.jp/",               "foodfish"),
    ("nippnhd",         "日本ハム",              "https://www.nipponham.co.jp/",            "foodfish"),
    ("itoham",          "伊藤ハム米久HD",        "https://www.itoham-yonekyu-hd.co.jp/",   "foodfish"),
    ("primaham",        "プリマハム",            "https://www.primaham.co.jp/",             "foodfish"),
    ("glico",           "江崎グリコ",            "https://www.glico.com/jp/",               "foodfish"),
    ("calbee",          "カルビー",              "https://www.calbee.co.jp/",               "foodfish"),
    ("morinaga_conf",   "森永製菓",              "https://www.morinaga.co.jp/",             "foodfish"),
    ("lotte",           "ロッテ",                "https://www.lotte.co.jp/",                "foodfish"),
    ("kameda",          "亀田製菓",              "https://www.kamedaseika.co.jp/",          "foodfish"),
    ("nisshin_seifun",  "日清製粉G",             "https://www.nisshin.com/",                "foodfish"),
    ("nippn",           "ニップン",              "https://www.nippn.co.jp/",                "foodfish"),
    ("yamazaki",        "山崎製パン",            "https://www.yamazakipan.co.jp/",          "foodfish"),
    ("maruhanichiiro",  "マルハニチロ",          "https://www.maruha-nichiro.co.jp/",       "foodfish"),
    ("nissui",          "ニッスイ",              "https://www.nissui.co.jp/",               "foodfish"),
    ("kyokuyou",        "極洋",                  "https://www.kyokuyo.co.jp/",              "foodfish"),

    # ── 農林 ─────────────────────────────────────────────────
    ("sakata_seed",     "サカタのタネ",          "https://www.sakataseed.co.jp/",           "agri"),
    ("kaneko_seed",     "カネコ種苗",            "https://www.kaneko.co.jp/",               "agri"),

    # ── 印刷・紙パルプ ───────────────────────────────────────
    ("toppan",          "TOPPANホールディングス","https://www.toppan.com/ja/",              "print"),
    ("dnp",             "大日本印刷",            "https://www.dnp.co.jp/",                  "print"),
    ("kyodo_print",     "共同印刷",              "https://www.kyodoprinting.co.jp/",        "print"),
    ("oji_paper",       "王子ホールディングス",  "https://www.ojiholdings.co.jp/",          "print"),
    ("nippon_paper",    "日本製紙",              "https://www.nipponpapergroup.com/",       "print"),
    ("rengo",           "レンゴー",              "https://www.rengo.co.jp/",                "print"),
    ("daio_paper",      "大王製紙",              "https://www.daio-paper.co.jp/",           "print"),

    # ── 化粧品・トイレタリー (new additions) ──────────────────
    ("milbon",          "ミルボン",              "https://www.milbon.co.jp/",               "cosme"),
    ("unicharm",        "ユニ・チャーム",        "https://www.unicharm.co.jp/ja/",          "cosme"),
    ("earth_chem",      "アース製薬",            "https://www.earth.jp/",                   "cosme"),

    # ── 医薬品 ───────────────────────────────────────────────
    ("tanabe_mitsubishi","田辺三菱製薬",         "https://www.mt-pharma.co.jp/",            "pharma2"),
    ("ono_pharma",      "小野薬品工業",          "https://www.ono.co.jp/",                  "pharma2"),
    ("shionogi",        "塩野義製薬",            "https://www.shionogi.com/jp/ja/",         "pharma2"),
    ("rohto_pharma",    "ロート製薬",            "https://www.rohto.co.jp/",                "pharma2"),
    ("santen",          "参天製薬",              "https://www.santen.co.jp/ja/",            "pharma2"),
    ("towa_pharma",     "東和薬品",              "https://www.towa-pharm.co.jp/",           "pharma2"),
    ("nippon_shinyaku", "日本新薬",              "https://www.nippon-shinyaku.co.jp/",      "pharma2"),
    ("kyorin",          "杏林製薬",              "https://www.kyorin-pharm.co.jp/",         "pharma2"),
    ("mochida",         "持田製薬",              "https://www.mochida.co.jp/",              "pharma2"),
    ("zeria",           "ゼリア新薬工業",        "https://www.zeria.co.jp/",                "pharma2"),
    ("sato_pharma",     "佐藤製薬",              "https://www.sato-seiyaku.co.jp/",         "pharma2"),

    # ── 化学 ─────────────────────────────────────────────────
    ("mitsubishi_chem",  "三菱ケミカル",         "https://www.m-chemical.co.jp/",           "chem"),
    ("fujifilm",        "富士フイルム",          "https://www.fujifilm.com/jp/ja/",         "chem"),
    ("asahi_kasei",     "旭化成グループ",        "https://www.asahi-kasei.co.jp/",          "chem"),
    ("sumitomo_chem",   "住友化学",              "https://www.sumitomo-chem.co.jp/",        "chem"),
    ("toray",           "東レ",                  "https://www.toray.co.jp/",                "chem"),
    ("mitsui_chem",     "三井化学",              "https://www.mitsuichem.com/jp/",          "chem"),
    ("resonac",         "レゾナック",            "https://www.resonac.com/jp/",             "chem"),
    ("sekisui_chem",    "積水化学工業",          "https://www.sekisui.co.jp/",              "chem"),
    ("tosoh",           "東ソー",                "https://www.tosoh.co.jp/",                "chem"),
    ("teijin",          "帝人",                  "https://www.teijin.co.jp/",               "chem"),
    ("kuraray",         "クラレ",                "https://www.kuraray.co.jp/",              "chem"),
    ("kaneka",          "カネカ",                "https://www.kaneka.co.jp/",               "chem"),
    ("mgc",             "三菱ガス化学",          "https://www.m-kagaku.co.jp/",             "chem"),
    ("daicel",          "ダイセル",              "https://www.daicel.com/",                 "chem"),
    ("ube_ind",         "UBE",                   "https://www.ube.co.jp/",                  "chem"),
    ("toyobo",          "東洋紡",                "https://www.toyobo.co.jp/",               "chem"),
    ("jsr",             "JSR",                   "https://www.jsr.co.jp/",                  "chem"),
    ("denka",           "デンカ",                "https://www.denka.co.jp/",                "chem"),
    ("tokuyama",        "トクヤマ",              "https://www.tokuyama.co.jp/",             "chem"),
    ("dic",             "DIC",                   "https://www.dic-global.com/ja/",          "chem"),
    ("kansai_paint",    "関西ペイント",          "https://www.kansai.co.jp/",               "chem"),
    ("nippon_paint_g",  "日本ペイントG",         "https://www.nipponpaint.co.jp/",          "chem"),
    ("sakata_ink",      "サカタインクス",        "https://www.sakata-ink.co.jp/",           "chem"),
    ("taiyo_nippon",    "大陽日酸",              "https://www.tn-gas.com/",                 "chem"),
    ("airwater",        "エア・ウォーター",      "https://www.aw-holdings.co.jp/",          "chem"),
    ("nippon_shokubai", "日本触媒",              "https://www.shokubai.co.jp/",             "chem"),
    ("nissan_chem",     "日産化学",              "https://www.nissanchem.co.jp/",           "chem"),

    # ── 衣料・繊維 ───────────────────────────────────────────
    ("seiren",          "セーレン",              "https://www.seiren.com/",                 "textile"),
    ("kurabo",          "クラボウ",              "https://www.kurabo.co.jp/",               "textile"),
    ("gunze",           "グンゼ",                "https://www.gunze.co.jp/",                "textile"),
    ("wacoal",          "ワコール",              "https://www.wacoal.jp/",                  "textile"),
    ("onward",          "オンワード樫山",        "https://www.onward.co.jp/",               "textile"),
    ("sanyo_shokai",    "三陽商会",              "https://www.sanyo-shokai.co.jp/",         "textile"),

    # ── ガラス・土石 ─────────────────────────────────────────
    ("agc",             "AGC",                   "https://www.agc.com/",                    "glass"),
    ("nippon_sheet",    "日本板硝子",            "https://www.nsg.co.jp/",                  "glass"),
    ("nippon_elec_glass","日本電気硝子",         "https://www.neg.co.jp/",                  "glass"),
    ("taiheiyo_cement", "太平洋セメント",        "https://www.taiheiyo-cement.co.jp/",      "glass"),
    ("nsk_ceramics",    "日本特殊陶業",          "https://www.ngkntk.co.jp/",               "glass"),
    ("ngk_insulators",  "日本ガイシ",            "https://www.ngk.co.jp/",                  "glass"),
    ("tokai_carbon",    "東海カーボン",          "https://www.tokaicarbon.co.jp/",          "glass"),
    ("noritake",        "ノリタケ",              "https://www.noritake.co.jp/",             "glass"),

    # ── 金属製品 ─────────────────────────────────────────────
    ("lixil",           "LIXIL",                 "https://www.lixil.co.jp/",                "metal"),
    ("ykk",             "YKK",                   "https://www.ykk.com/japan/",              "metal"),
    ("toyo_seikan",     "東洋製罐グループHD",    "https://www.toyo-seikan.co.jp/",          "metal"),
    ("ykk_ap",          "YKK AP",                "https://www.ykkap.co.jp/",                "metal"),
    ("sumco",           "SUMCO",                 "https://www.sumcosi.com/",                "metal"),
    ("bunka_shutter",   "文化シヤッター",        "https://www.bunka-shutter.co.jp/",        "metal"),

    # ── 鉄鋼 ─────────────────────────────────────────────────
    ("nippon_steel",    "日本製鉄",              "https://www.nipponsteel.com/",            "steel"),
    ("jfe_steel",       "JFEスチール",           "https://www.jfe-steel.co.jp/",            "steel"),
    ("kobe_steel",      "神戸製鋼所",            "https://www.kobelco.co.jp/",              "steel"),
    ("proterial",       "プロテリアル",          "https://www.proterial.com/",              "steel"),
    ("daido_steel",     "大同特殊鋼",            "https://www.daido.co.jp/",                "steel"),
    ("aichi_steel",     "愛知製鋼",              "https://www.aichi-steel.co.jp/",          "steel"),
    ("mitsubishi_steel","三菱製鋼",              "https://www.mitsubishi-steel.co.jp/",     "steel"),

    # ── 非鉄金属 ─────────────────────────────────────────────
    ("sumitomo_elec",   "住友電気工業",          "https://www.sei.co.jp/",                  "nonferrous"),
    ("furukawa_elec",   "古河電気工業",          "https://www.furukawa.co.jp/",             "nonferrous"),
    ("fujikura",        "フジクラ",              "https://www.fujikura.co.jp/",             "nonferrous"),
    ("mitsubishi_mat",  "三菱マテリアル",        "https://www.mmc.co.jp/",                  "nonferrous"),
    ("sumitomo_metal",  "住友金属鉱山",          "https://www.smm.co.jp/",                  "nonferrous"),
    ("jx_metals",       "JX金属",                "https://www.jx-metals.com/",              "nonferrous"),
    ("mitsui_mining",   "三井金属",              "https://www.mitsui-kinzoku.co.jp/",       "nonferrous"),
    ("dowa",            "DOWAホールディングス",  "https://www.dowa.co.jp/",                 "nonferrous"),
    ("uacj",            "UACJ",                  "https://www.uacj.co.jp/",                 "nonferrous"),
    ("nlmk_jp",         "日本軽金属",            "https://www.nikkeikin.co.jp/",            "nonferrous"),

    # ── その他メーカー ───────────────────────────────────────
    ("asics",           "アシックス",            "https://www.asics.com/jp/ja-jp/",         "othermfg"),
    ("mizuno",          "ミズノ",                "https://www.mizuno.jp/",                  "othermfg"),
    ("yonex",           "ヨネックス",            "https://www.yonex.co.jp/",                "othermfg"),
    ("takara_tomy",     "タカラトミー",          "https://www.takaratomy.co.jp/",           "othermfg"),
    ("bandai",          "バンダイ",              "https://www.bandai.co.jp/",               "othermfg"),
    ("pigeon",          "ピジョン",              "https://www.pigeon.co.jp/",               "othermfg"),
    ("yamaha_corp",     "ヤマハ",                "https://jp.yamaha.com/",                  "othermfg"),
    ("roland",          "ローランド",            "https://www.roland.com/jp/",              "othermfg"),
    ("kawai",           "河合楽器",              "https://jp.kawai.co.jp/",                 "othermfg"),
    ("toto",            "TOTO",                  "https://www.toto.co.jp/",                 "othermfg"),
    ("rinnai",          "リンナイ",              "https://www.rinnai.co.jp/",               "othermfg"),
    ("noritz",          "ノーリツ",              "https://www.noritz.co.jp/",               "othermfg"),
    ("takara_standard", "タカラスタンダード",    "https://www.takara-standard.co.jp/",      "othermfg"),
    ("cleanup",         "クリナップ",            "https://cleanup.jp/",                     "othermfg"),
    ("kokuyo",          "コクヨ",                "https://www.kokuyo.co.jp/",               "othermfg"),
    ("pilot",           "パイロットコーポレーション","https://www.pilot.co.jp/",            "othermfg"),
    ("mitsubishi_pencil","三菱鉛筆",             "https://www.mpuni.co.jp/",                "othermfg"),
    ("okamura",         "オカムラ",              "https://www.okamura.co.jp/",              "othermfg"),
    ("itoki",           "イトーキ",              "https://www.itoki.jp/",                   "othermfg"),
    ("daiken",          "DAIKEN",                "https://www.daiken.jp/",                  "othermfg"),

    # ── 建設 ─────────────────────────────────────────────────
    ("kajima",          "鹿島",                  "https://www.kajima.co.jp/",               "construction"),
    ("obayashi",        "大林組",                "https://www.obayashi.co.jp/",             "construction"),
    ("taisei",          "大成建設",              "https://www.taisei.co.jp/",               "construction"),
    ("shimizu",         "清水建設",              "https://www.shimz.co.jp/",                "construction"),
    ("takenaka",        "竹中工務店",            "https://www.takenaka.co.jp/",             "construction"),
    ("haseko",          "長谷工コーポレーション","https://www.haseko.co.jp/",               "construction"),
    ("maeda_const",     "前田建設工業",          "https://www.maeda.co.jp/",                "construction"),
    ("toda",            "戸田建設",              "https://www.toda.co.jp/",                 "construction"),
    ("fujita",          "フジタ",                "https://www.fujita.co.jp/",               "construction"),
    ("kumagai",         "熊谷組",                "https://www.kumagai.co.jp/",              "construction"),
    ("smscc",           "三井住友建設",          "https://www.smcon.co.jp/",                "construction"),
    ("ando_hazama",     "安藤ハザマ",            "https://www.andoh.co.jp/",                "construction"),
    ("nishimatsu",      "西松建設",              "https://www.nishimatsu.co.jp/",           "construction"),
    ("okumura",         "奥村組",                "https://www.okumura.co.jp/",              "construction"),
    ("kfc_const",       "鴻池組",                "https://www.konoike.co.jp/",              "construction"),
    ("tokyu_const",     "東急建設",              "https://www.tokyu-cnst.co.jp/",           "construction"),
    ("nikki",           "日揮ホールディングス",  "https://www.jgc.com/jp/",                 "construction"),
    ("jfe_eng",         "JFEエンジニアリング",   "https://www.jfe-eng.co.jp/",              "construction"),
    ("chiyoda",         "千代田化工建設",        "https://www.chiyoda-corp.com/",           "construction"),
    ("toyo_eng",        "東洋エンジニアリング",  "https://www.toyo-eng.com/jp/",            "construction"),
    ("ntt_fac",         "NTTファシリティーズ",   "https://www.ntt-f.co.jp/",                "construction"),
    ("sanki_eng",       "三機工業",              "https://www.sanki.co.jp/",                "construction"),
    ("kimden",          "きんでん",              "https://www.kinden.co.jp/",               "construction"),
    ("kandenko",        "関電工",                "https://www.kandenko.co.jp/",             "construction"),
    ("toenec",          "トーエネック",          "https://www.toenec.co.jp/",               "construction"),
    ("yurtec",          "ユアテック",            "https://www.yurtec.co.jp/",               "construction"),
    ("exeo",            "エクシオグループ",      "https://www.exeo.co.jp/",                 "construction"),
    ("miraite",         "ミライト・ワン",        "https://www.mirait-one.com/",             "construction"),
    ("nihon_comsis",    "日本コムシス",          "https://www.ncs.co.jp/",                  "construction"),

    # ── 住宅・マンション ──────────────────────────────────────
    ("daito_kentaku",   "大東建託G",             "https://www.kentaku.co.jp/",              "housing"),
    ("ichijo",          "一条工務店",            "https://www.ichijo.co.jp/",               "housing"),
    ("misawa",          "ミサワホーム",          "https://www.misawa.co.jp/",               "housing"),
    ("panasonic_homes", "パナソニックホームズ",  "https://homes.panasonic.com/",            "housing"),
    ("toyota_home",     "トヨタホーム",          "https://www.toyotahome.co.jp/",           "housing"),
    ("mitsui_res",      "三井不動産レジデンシャル","https://www.mfr.co.jp/",                "housing"),
    ("anabuki",         "穴吹興産",              "https://www.anabuki-m.co.jp/",            "housing"),
    ("daikyo",          "大京",                  "https://www.daikyo.co.jp/",               "housing"),
    ("starts",          "スターツグループ",      "https://www.starts.co.jp/",               "housing"),

    # ── 不動産 ────────────────────────────────────────────────
    ("hulic",           "ヒューリック",          "https://www.hulic.co.jp/",                "realestate"),
    ("tokyo_tatemono",  "東京建物",              "https://www.tatemono.com/",               "realestate"),
    ("aeon_mall",       "イオンモール",          "https://www.aeon-mall.co.jp/",            "realestate"),
    ("mori_building",   "森ビル",                "https://www.mori.co.jp/",                 "realestate"),
    ("mori_trust",      "森トラスト",            "https://www.mori-trust.co.jp/",           "realestate"),
    ("ntt_urban",       "NTT都市開発",           "https://www.nttud.co.jp/",                "realestate"),

    # ── 電力・ガス ────────────────────────────────────────────
    ("hokkaido_elec",   "北海道電力",            "https://www.hepco.co.jp/",                "energy"),
    ("tohoku_elec",     "東北電力",              "https://www.tohoku-epco.co.jp/",          "energy"),
    ("jera",            "JERA",                  "https://www.jera.co.jp/",                 "energy"),
    ("jpower",          "Jパワー",               "https://www.jpower.co.jp/",               "energy"),
    ("hokuriku_elec",   "北陸電力",              "https://www.rikuden.co.jp/",              "energy"),
    ("chubu_elec",      "中部電力",              "https://www.chuden.co.jp/",               "energy"),
    ("chugoku_elec",    "中国電力",              "https://www.energia.co.jp/",              "energy"),
    ("shikoku_elec",    "四国電力",              "https://www.yonden.co.jp/",               "energy"),
    ("okinawa_elec",    "沖縄電力",              "https://www.okiden.co.jp/",               "energy"),
    ("tokyo_gas_new",   "東京ガス",              "https://www.tokyo-gas.co.jp/",            "energy"),
    ("osaka_gas",       "大阪ガス",              "https://www.osakagas.co.jp/",             "energy"),
    ("saibu_gas",       "西部ガス",              "https://www.saibugas.co.jp/",             "energy"),

    # ── 石油 ─────────────────────────────────────────────────
    ("eneos",           "ENEOS",                 "https://www.eneos.co.jp/",                "oil"),
    ("idemitsu",        "出光興産",              "https://www.idemitsu.com/jp/",            "oil"),
    ("cosmo",           "コスモ石油",            "https://www.cosmo-oil.co.jp/",            "oil"),
    ("inpex",           "INPEX",                 "https://www.inpex.co.jp/",                "oil"),

    # ── デパート ─────────────────────────────────────────────
    ("daimaru",         "大丸松坂屋百貨店",      "https://www.daimaru.co.jp/",              "dept"),
    ("takashimaya",     "髙島屋",                "https://www.takashimaya.co.jp/",          "dept"),
    ("isetan_mitsukoshi","三越伊勢丹",           "https://www.imhds.co.jp/",                "dept"),
    ("marui",           "丸井グループ",          "https://www.0101maruigroup.co.jp/",       "dept"),
    ("hankyu_hanshin_dept","阪急阪神百貨店",     "https://www.hankyu-hanshin-dept.co.jp/",  "dept"),
    ("tokyu_dept",      "東急百貨店",            "https://www.tokyu-dept.co.jp/",           "dept"),
    ("kintetsu_dept",   "近鉄百貨店",            "https://www.d-kintetsu.co.jp/",           "dept"),
    ("sogo_seibu",      "そごう・西武",          "https://www.sogo-seibu.co.jp/",           "dept"),
    ("odakyu_dept",     "小田急百貨店",          "https://www.odakyu-dept.co.jp/",          "dept"),
    ("matsuya_dept",    "松屋",                  "https://www.matsuya.com/",                "dept"),

    # ── コンビニ ─────────────────────────────────────────────
    ("lawson",          "ローソン",              "https://www.lawson.co.jp/",               "convenience"),
    ("seven_eleven",    "セブン-イレブン・ジャパン","https://www.sej.co.jp/",               "convenience"),
    ("family_mart",     "ファミリーマート",      "https://www.family.co.jp/",               "convenience"),
    ("mini_stop",       "ミニストップ",          "https://www.ministop.co.jp/",             "convenience"),

    # ── スーパー ─────────────────────────────────────────────
    ("itoyokado",       "イトーヨーカ堂",        "https://www.itoyokado.co.jp/",            "supermarket"),
    ("fuji_retail",     "フジ",                  "https://www.fujishoji.co.jp/",            "supermarket"),
    ("izumi",           "イズミ",                "https://www.the-izumi.co.jp/",            "supermarket"),
    ("heiwado",         "平和堂",                "https://www.heiwado.jp/",                 "supermarket"),
    ("yaoko",           "ヤオコー",              "https://www.yaoko-net.com/",              "supermarket"),
    ("belc",            "ベルク",                "https://www.belc.jp/",                    "supermarket"),
    ("inageya",         "いなげや",              "https://www.inageya.co.jp/",              "supermarket"),
    ("summit",          "サミット",              "https://www.summitstore.co.jp/",          "supermarket"),
    ("tokyu_store",     "東急ストア",            "https://www.tokyu-store.co.jp/",          "supermarket"),
    ("life_corp",       "ライフコーポレーション","https://www.lifecorp.jp/",                "supermarket"),
    ("kobebusan",       "神戸物産",              "https://www.kobebussan.co.jp/",           "supermarket"),
    ("hellos",          "ハローズ",              "https://www.hallows.co.jp/",              "supermarket"),

    # ── 外食・中食 ────────────────────────────────────────────
    ("skylark",         "すかいらーくHD",        "https://www.skylark.co.jp/",              "restaurant"),
    ("matsuya_foods",   "松屋フーズ",            "https://www.matsuyafoods.co.jp/",         "restaurant"),
    ("doutor",          "ドトールコーヒー",      "https://www.doutor.co.jp/",               "restaurant"),
    ("rock_field",      "ロック・フィールド",    "https://www.rockfield.co.jp/",            "restaurant"),

    # ── 家電量販・薬局・HC ───────────────────────────────────
    ("nojima",          "ノジマ",                "https://www.nojima.co.jp/",               "retail3"),
    ("edion",           "エディオン",            "https://www.edion.co.jp/",                "retail3"),
    ("matsukiyo",       "マツキヨCC",            "https://www.matsukiyococokara.com/",      "retail3"),
    ("sugi_pharmacy",   "スギ薬局",              "https://www.sugi-net.jp/",                "retail3"),
    ("tsuruha",         "ツルハ",                "https://www.tsuruha.co.jp/",              "retail3"),
    ("cainz",           "カインズ",              "https://www.cainz.co.jp/",                "retail3"),
    ("dcm",             "DCM",                   "https://www.dcm-hldgs.co.jp/",            "retail3"),
    ("konan",           "コーナン商事",          "https://www.konan-group.co.jp/",          "retail3"),

    # ── その他小売 ───────────────────────────────────────────
    ("donki",           "ドン・キホーテ",        "https://www.donki.com/",                  "otherretail"),
    ("shimamura",       "しまむら",              "https://www.shimamura.gr.jp/",            "otherretail"),
    ("abc_mart",        "ABCマート",             "https://www.abc-mart.net/",               "otherretail"),
    ("nishimatsuya",    "西松屋チェーン",        "https://www.24028.jp/",                   "otherretail"),
    ("aoyama",          "青山商事",              "https://www.aoyama-syoji.co.jp/",         "otherretail"),
    ("aoki_hd",         "AOKIホールディングス",  "https://www.aoki-hd.co.jp/",              "otherretail"),
    ("yanase",          "ヤナセ",                "https://www.yanase.co.jp/",               "otherretail"),
    ("alpen",           "アルペン",              "https://www.alpen-group.jp/",             "otherretail"),
    ("xebio",           "ゼビオ",                "https://www.xebio.co.jp/",                "otherretail"),
    ("bookoff",         "ブックオフコーポレーション","https://www.bookoffonline.co.jp/",     "otherretail"),
    ("nitori_new",      "ニトリグループ",        "https://www.nitori-hd.co.jp/",            "otherretail"),
    ("askul",           "アスクル",              "https://www.askul.co.jp/",                "otherretail"),

    # ── ゲーム ───────────────────────────────────────────────
    ("konami",          "コナミグループ",        "https://www.konami.com/ja/",              "gaming"),

    # ── 人材・教育 ────────────────────────────────────────────
    ("meitec",          "メイテック",            "https://www.meitec.co.jp/",               "hred"),
    ("alps_giken",      "アルプス技研",          "https://www.alpsgiken.co.jp/",            "hred"),
    ("keio",            "慶應義塾",              "https://www.keio.ac.jp/",                 "hred"),
    ("waseda",          "早稲田大学",            "https://www.waseda.jp/",                  "hred"),
    ("ritsumeikan",     "立命館",                "https://www.ritsumei.ac.jp/",             "hred"),
    ("meiji_univ",      "明治大学",              "https://www.meiji.ac.jp/",                "hred"),
    ("hosei",           "法政大学",              "https://www.hosei.ac.jp/",                "hred"),
    ("chuo_univ",       "中央大学",              "https://www.chuo-u.ac.jp/",               "hred"),
    ("toyo_univ",       "東洋大学",              "https://www.toyo.ac.jp/",                 "hred"),
    ("rikkyo",          "立教学院",              "https://www.rikkyo.ac.jp/",               "hred"),
    ("kumon",           "公文教育研究会",        "https://www.kumon.co.jp/",                "hred"),

    # ── ホテル ───────────────────────────────────────────────
    ("seibu_prince",    "西武・プリンスホテルズ","https://www.princehotels.co.jp/",          "hotel"),
    ("fujita_kanko",    "藤田観光",              "https://www.fujita-kanko.co.jp/",         "hotel"),
    ("new_otani",       "ニュー・オータニ",      "https://www.newotani.co.jp/",             "hotel"),
    ("imperial",        "帝国ホテル",            "https://www.imperialhotel.co.jp/",        "hotel"),
    ("okura",           "ホテルオークラ東京",    "https://www.hotelokura.co.jp/tokyo/",     "hotel"),

    # ── レジャー ─────────────────────────────────────────────
    ("his",             "エイチ・アイ・エス",    "https://www.his-j.com/",                  "leisure"),
    ("hankyu_travel",   "阪急交通社",            "https://www.hankyu-travel.com/",          "leisure"),
    ("nippon_travel",   "日本旅行",              "https://www.nta.co.jp/",                  "leisure"),
    ("oriental_land",   "オリエンタルランド",    "https://www.olc.co.jp/ja/",               "leisure"),
    ("round1",          "ラウンドワンジャパン",  "https://www.round1.co.jp/",               "leisure"),
    ("tokyo_dome",      "東京ドーム",            "https://www.tokyo-dome.co.jp/",           "leisure"),
    ("toei",            "東映",                  "https://www.toei.co.jp/",                 "leisure"),
    ("shochiku",        "松竹",                  "https://www.shochiku.co.jp/",             "leisure"),
    ("renaissance",     "ルネサンス",            "https://www.s-renaissance.co.jp/",        "leisure"),
    ("central_sports",  "セントラルスポーツ",    "https://www.central.co.jp/",              "leisure"),

    # ── 海運・空運 ────────────────────────────────────────────
    ("nyk",             "日本郵船",              "https://www.nyk.com/",                    "seaair"),
    ("mol",             "商船三井",              "https://www.mol.co.jp/",                  "seaair"),
    ("k_line",          "川崎汽船",              "https://www.kline.co.jp/",                "seaair"),
    ("iino",            "飯野海運",              "https://www.iino.co.jp/",                 "seaair"),

    # ── 運輸・倉庫 ────────────────────────────────────────────
    ("nittsu",          "日本通運",              "https://www.nittsu.co.jp/",               "logistics"),
    ("seino",           "西濃運輸",              "https://www.seino.co.jp/",                "logistics"),
    ("fukuyama",        "福山通運",              "https://corp.fukuyama-transporting.co.jp/","logistics"),
    ("tonami",          "トナミ運輸",            "https://www.tonami.co.jp/",               "logistics"),
    ("logisteed",       "ロジスティード",        "https://www.logisteed.com/",              "logistics"),
    ("senko",           "センコー",              "https://www.senko.co.jp/",                "logistics"),
    ("sankyu",          "山九",                  "https://www.sankyu.co.jp/",               "logistics"),
    ("konoike_trans",   "鴻池運輸",              "https://www.konoike.co.jp/",              "logistics"),
    ("yusen_log",       "郵船ロジスティクス",    "https://www.yusen-logistics.com/",        "logistics"),
    ("kintetsu_exp",    "近鉄エクスプレス",      "https://www.kwe.co.jp/",                  "logistics"),
    ("uenogumi",        "上組",                  "https://www.uenogumi.co.jp/",             "logistics"),
    ("mitsubishi_wh",   "三菱倉庫",              "https://www.mitsubishi-logistics.co.jp/", "logistics"),
    ("mitsui_wh",       "三井倉庫HD",            "https://www.mitsui-soko.co.jp/",          "logistics"),
    ("sumitomo_wh",     "住友倉庫",              "https://www.sumitomo-soko.co.jp/",        "logistics"),

    # ── 鉄道 ─────────────────────────────────────────────────
    ("jr_hokkaido",     "北海道旅客鉄道",        "https://www.jrhokkaido.co.jp/",           "railway"),
    ("seibu_railway",   "西武鉄道",              "https://www.seiburailway.jp/",            "railway"),
    ("keisei",          "京成電鉄",              "https://www.keisei.co.jp/",               "railway"),
    ("tokyu_train",     "東急",                  "https://www.tokyu.co.jp/",                "railway"),
    ("seibu_hd",        "西武ホールディングス",  "https://www.seibu-hd.co.jp/",             "railway"),
    ("tobu",            "東武鉄道",              "https://www.tobu.co.jp/",                 "railway"),
    ("keio",            "京王電鉄",              "https://www.keio.co.jp/",                 "railway"),
    ("odakyu",          "小田急電鉄",            "https://www.odakyu.jp/",                  "railway"),
    ("tokyo_metro",     "東京地下鉄",            "https://www.tokyometro.jp/",              "railway"),
    ("jr_freight",      "日本貨物鉄道",          "https://www.jrfreight.co.jp/",            "railway"),
    ("keikyu",          "京浜急行電鉄",          "https://www.keikyu.co.jp/",               "railway"),
    ("meitetsu",        "名古屋鉄道",            "https://www.meitetsu.co.jp/",             "railway"),
    ("kintetsu_hd",     "近鉄グループHD",        "https://www.kintetsu.co.jp/",             "railway"),
    ("hankyu_hanshin",  "阪急阪神HD",            "https://www.hankyu-hanshin.co.jp/",       "railway"),
    ("keihan_hd",       "京阪HD",                "https://www.keihan-hd.co.jp/",            "railway"),
    ("nankai",          "南海電気鉄道",          "https://www.nankai.co.jp/",               "railway"),
    ("osaka_metro",     "大阪市高速電気軌道",    "https://www.osakametro.co.jp/",           "railway"),
    ("jr_shikoku",      "四国旅客鉄道",          "https://www.jr-shikoku.co.jp/",           "railway"),
    ("jr_kyushu",       "九州旅客鉄道",          "https://www.jrkyushu.co.jp/",             "railway"),
    ("nishitetsu",      "西日本鉄道",            "https://www.nnr.co.jp/",                  "railway"),

    # ── その他サービス ───────────────────────────────────────
    ("nexco_east",      "東日本高速道路",        "https://www.e-nexco.co.jp/",              "otherservice"),
    ("shutoko",         "首都高速道路",          "https://www.shutoko.co.jp/",              "otherservice"),
    ("nexco_central",   "中日本高速道路",        "https://www.c-nexco.co.jp/",              "otherservice"),
    ("nexco_west",      "西日本高速道路",        "https://www.w-nexco.co.jp/",              "otherservice"),
    ("hanshin_exp",     "阪神高速道路",          "https://www.hanshin-exp.co.jp/",          "otherservice"),
    ("jp_post_hd",      "日本郵政",              "https://www.japanpost.jp/",               "otherservice"),
    ("aist",            "産業技術総合研究所",    "https://www.aist.go.jp/",                 "otherservice"),
    ("jaf",             "日本自動車連盟(JAF)",   "https://jaf.or.jp/",                      "otherservice"),
    ("secom",           "セコム",                "https://www.secom.co.jp/",                "otherservice"),
    ("alsok",           "ALSOK",                 "https://www.alsok.co.jp/",                "otherservice"),
    ("duskin",          "ダスキン",              "https://www.duskin.co.jp/",               "otherservice"),
    ("recruit_new",     "リクルート",            "https://www.recruit.co.jp/",              "otherservice"),
    ("jica",            "JICA",                  "https://www.jica.go.jp/",                 "otherservice"),
    ("jetro",           "JETRO",                 "https://www.jetro.go.jp/",                "otherservice"),
    ("jaxa",            "JAXA",                  "https://www.jaxa.jp/",                    "otherservice"),
    ("jec_hd",          "関東電気保安協会",      "https://www.kdh.or.jp/",                  "otherservice"),
]

# ── Output ──────────────────────────────────────────────────────────

print("// ── NEW INDUSTRIES ────────────────────────────────────────")
for iid, label in NEW_INDUSTRIES:
    print(f'      {iid}: "{label}",')

print("\n// ── NEW COMPANIES ─────────────────────────────────────────")
seen_ids = set()
for (cid, name, url, iid) in COMPANIES_NEW:
    if cid in EXISTING or cid in seen_ids:
        continue
    seen_ids.add(cid)
    print(f'      {cid}: "{name}",')

print("\n// ── NEW RAW ROWS ───────────────────────────────────────────")
seen_raw = set()
for (cid, name, url, iid) in COMPANIES_NEW:
    if cid in EXISTING:
        continue
    if cid in seen_raw:
        continue
    seen_raw.add(cid)
    print(f'      ["{iid}", "{cid}", "TOPページ", "{url}", null],')
    print(f'      ["{iid}", "{cid}", "企業情報", "{url}company/", null],')
    print(f'      ["{iid}", "{cid}", "採用情報", "{url}recruit/", null],')

print(f"\n// Total new companies: {len(seen_raw)}")
